name: Web
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REGION: us-central1
on:
  workflow_dispatch: {}
  push:
     paths:
       - web
       - .github/workflows/web.yaml
jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        working-directory: web
        run: npm ci
      - name: Build
        working-directory: web
        run: npm run build
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: deploy_dist
          path: web/dist/web/
  deploy-dev:
    name: Deploy dev env
    runs-on: ubuntu-latest
    needs: [build]
    environment: dev
    steps:
      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: dev
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: actions/download-artifact@v2
        with:
          name: deploy_dist
          path: web/
      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: web/*
          destination: ${{secrets.SPA_BUCKET_NAME}}
      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}