name: Web
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REGION: us-central1
on:
  workflow_dispatch: {}
  push:
     paths:
       - web
       - .github/workflows/web.yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        working-directory: web
        run: npm ci
      - name: Build
        working-directory: web
        run: npm run build
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: deploy_dist
          path: web/dist/web/